
services:
  - type: web
    name: telegram-discount-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: BOT_TOKEN
        value: "8017053987:AAE9vEiYCFmAZd4KeQ1eRuCjNgCbnKHWKhk"
